### ISSUE TITLE
Update after async function in controller constructor hot-reload crash.

### ISSUE THREAD

**Issue by aka-coke** [jonataslaw/get#112]
I don't know if this is a bug or I'm doing something wrong but calling update after an async function inside a controller's constructor crashes the app when hot reloading.

My controller is something like this:
```
class Controller extends GetController {
  Controller() {
    _loadSomething();
  }

  _loadSomething() async {
    await initializeSomething();
    update(this);
  }
}
```

Then I use this just like in docs:
```
[...]
return GetBuilder<Controller>(
  init: Controller(),
  builder: (_) {},
);
```

This all works fine if I just use the app but the moment I hot-reload, it crashes with this exception:
```
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'forEach' was called on null.
Receiver: null
Tried calling: forEach(Closure: (RealState) => Null))
```

Somehow, the `all` variable inside the `update` method is null with the `_allStates` map empty.

My use-case is that I want to render something after the loading ends. The data that I want is empty at start so I just check inside my widget `controller.data.isNotEmpty ? DataWidget : NoDataWIdget`. Is this the right way to do this or should I just do it using `FutureBuilder`? Will there be some performance issue just like the ones you stated about the `StreamBuilder` if I use `FutureBuilder`?

**Comment by jonataslaw** [comment]
StreamBuilder has no performance problem, I just don't recommend using StreamControllers for lists, because each StreamBuilder takes up 1mb of memory (1024kb to be more exact), and a BehaviorSubject somewhere around 1300kb. Many people to change a single button in a list, use a StreamController, and this is harmful, because the lists will be generated dynamically, and the memory allocation for the StreamControllers will be huge.

With GetX I was able to get around this performance problem by creating a single StreamController for the entire app, and adding StreamSubscriptions within GetX, which listens to the events of that single StreamController. The memory usage of the subscriptions are very low, so I ended up managing to reconcile reactive programming with performance. StreamControllers in a controlled way are not a problem, the problem is you generate lists of widgets with them inside, or use a generator generator for each item in the list, and insert StreamControllers inside.
I'll try to reproduce your error, but I'll tell you something, you are putting methods in constructors, I know that this is practically standard in all languages, but in Flutter, for example, it is preferable to call methods from initState. In order to follow Flutter's recommendations, I added the "onInit" method inside the controllers to avoid using constructors to initialize methods. This is important to avoid duplication, because who will "emit" the init event is the GetBuilder, even if it is done without you noticing. And the Controller will update the GetBuilder "state". This follows consolidated state management standards at Google I/O June 2019.

**Comment by jonataslaw** [comment]
Just one question, are you using init in just one place? If you use the init of the same controller in two places, you will implode the Get algorithm for removing controllers from memory, and this will have undesired effects, such as, the controller being null because it was disposed.

**Comment by aka-coke** [comment]
I see. I understand. Thank you! DIdn't know I was using 2.4.0 of get so I didn't see that `onInit` method. WIll try using that. Thanks! Closing this.
