### ISSUE TITLE
show SnackBar when unknownRoute

### ISSUE THREAD

**Issue by WingCH** [jonataslaw/get#113]
I want show SnackBar when unknownRoute.
![image](https://user-images.githubusercontent.com/19588517/82137772-9650c180-984d-11ea-9e79-2bd8eec340cd.png)

I tried overwrite `onUnknownRoute`, but seems not work.
I cannot call showSnackBar in `unknownRoute` .

**Comment by jonataslaw** [comment]
onUnknownRoute receives a route, so the only way to make this possible is to call a new route and start the snackbar on it.

**Comment by WingCH** [comment]
I tried overwrite `onUnknownRoute`, but it didn't work, the page go to `Route not found :(` page directly

```dart
// ignore: missing_return
onUnknownRoute: (_) {
    print('onUnknownRoute');
    Get.snackbar('Hi', 'i am a modern snackbar');
}),
```

![photo_2020-05-17 15 36 48](https://user-images.githubusercontent.com/19588517/82138606-41fd1000-9854-11ea-9081-afce55632d53.jpeg)

**Comment by jonataslaw** [comment]
onUnknownRoute receives a route, so the only way to make this possible is to call a new route and start the snackbar on it. (2)

If you want a snackbar to appear, do so, remembering that you cannot use namedRoutes or dynamic routes if you choose to use onGenerateRoutes.

```dart
void main() {
  runApp(GetMaterialApp(
      onGenerateRoute: (settings) {
        if (settings.name == '/') {
          return GetRouteBase(page: First());
        } else {
          return SnackRoute(
              snack: GetBar(
            message: "page not found",
            duration: Duration(seconds: 3),
          ));
        }
      },
      home: First()));
}
```

I do not recommend any of this, just because I think it is a bad approach, and although snackbars, dialogs, and bottomsheets are navigation elements because it is a stack, this is very anti pattern. You will never browse a website with a nonexistent url. But if your project needs it ...
Anyway, closing this.
