### ISSUE TITLE
Animation Controller with TickerProviderStateMixin

### ISSUE THREAD

**Issue by jemariads** [jonataslaw/get#117]
hi @jonataslaw 
first I wanna say thank you for great package Get,

as you said  "Forget StatefulWidget", but how we create GetController for Animation Controller where we need TickerProviderStateMixin ?

example :

```
 class BottomBarView extends StatefulWidget {
   @override
   _BottomBarViewState createState() => _BottomBarViewState();
 }
 
 class _BottomBarViewState extends State<BottomBarView>
     with TickerProviderStateMixin {
   AnimationController animationController;
 
   @override
   void initState() {
     animationController = AnimationController(
       vsync: this,
       duration: const Duration(milliseconds: 1000),
     );
     animationController.forward();
     super.initState();
   }
 
   @override
   Widget build(BuildContext context) {
     return Scaffold(
     );
   }
}
```

**Comment by jonataslaw** [comment]
> hi @jonataslaw
> first I wanna say thank you for great package Get,
> 
> as you say "Forget StatefulWidget", but how we create GetController for Animation Controller where we need TickerProviderStateMixin ?
> 
> example :
> 
> > class BottomBarView extends StatefulWidget {
> > @override
> > _BottomBarViewState createState() => _BottomBarViewState();
> > }
> > class _BottomBarViewState extends State
> > with TickerProviderStateMixin {
> > AnimationController animationController;
> > @override
> > void initState() {
> > animationController = AnimationController(
> > vsync: this,
> > duration: const Duration(milliseconds: 1000),
> > );
> > animationController.forward();
> > super.initState();
> > }
> > @override
> > Widget build(BuildContext context) {
> > return Scaffold(
> > );
> > }
> > }

Actually there is no problem using StatefulWidget, but I needed to draw some attention to this, because in an app with a single FlatButton on the desktop Flutter that is now open, a StatelessWidget consumes 1mb and the same StatefulWidget class consumes 2mb. The difference is exactly double, so reducing the number of classes with StatefulWidget can significantly improve RAM consumption.
However, if one of the requirements of the class is to use StatefulWidget, there will be no problem using it, I would just say to create a separate widget for this component to make your code more readable and that is exactly what you did. Great!

**Comment by ialameh** [comment]
I needed vsync to setup a controller for the tabbar, and looked inside the get package code and what worked with me is: 

vsync: Navigator()

**Comment by ghprod** [comment]
> I needed vsync to setup a controller for the tabbar, and looked inside the get package code and what worked with me is:
> 
> vsync: Navigator()

For me is `TabController tabController = TabController(length: 10, vsync: NavigatorState());`

Hope can help someone :+1:

**Comment by ehsanbigzad** [comment]
> > I needed vsync to setup a controller for the tabbar, and looked inside the get package code and what worked with me is:
> > vsync: Navigator()
> 
> For me is `TabController tabController = TabController(length: 10, vsync: NavigatorState());`
> 
> Hope can help someone 👍

@ghprod, you saved my life bro :)

**Comment by cyriacbijun** [comment]
@ghprod Thank you for the brilliant solution, it worked for me until flutter 2.8.2. After upgrading to flutter 2.10 it no longer works, so the workaround was to use `Navigator.of(Get.context!)` instead of `NavigatorState()`. But I feel both of these are temporary solutions. Can someone suggest some mechanism by which we can use animation controllers that is encapsulated in another class? We require more than 1 animation controller.
