### ISSUE TITLE
Can't get arguments in ViewModel

### ISSUE THREAD

**Issue by Jethro87** [jonataslaw/get#122]
I'm getting errors when trying to access my arguments via Get.arguments in my viewmodels. This issue does not occur in the view itself. Here's an example:

## Viewmodel
```
class EntryViewModel extends BaseViewModel {
  EntryViewModel({
    @required this.entry,
    this.index,
    this.isNew,
    this.isReviewing,
  });

  final EntryViewArguments args = Get.arguments;
  final Entry entry1 = args.entry;
```

`args` in `entry1` is underlined and says `Only static members can be accessed in initializers.`.

If I change the above code to::

```
class EntryViewModel extends BaseViewModel {
  EntryViewModel({
    @required this.entry,
    this.index,
    this.isNew,
    this.isReviewing,
  });

  final Entry entry1 = Get.arguments.entry;
```
`entry` is underlined and says `The getter 'entry' isn't defined for the type 'Object'.
Try importing the library that defines 'entry', correcting the name to the name of an existing getter, or defining a getter or field named 'entry'`.

## View
On the other hand, I get none of these errors when trying to read the arguments in a view. 

```
class EntryView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final EntryViewArguments args = Get.arguments;
    final Entry entry1 = args.entry;
```

This works perfectly fine, with no warnings/errors.

## Model
For reference, the `EntryViewArguments` model looks like this:

```
class EntryViewArguments {
  EntryViewArguments({
    @required this.entry,
    this.index,
    this.isNew,
    this.isReviewing,
  });

  final Entry entry;
  final int index;
  final bool isNew;
  final bool isReviewing;
}
```

## Main
And my main function:

```
GetMaterialApp(
          navigatorObservers: <NavigatorObserver>[
            locator<AnalyticsService>().observer,
          ],
          initialRoute: Routes.startupView,
          namedRoutes: Router.namedRoutes,
```

## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
```
## Get version
2.5.6

**Comment by jonataslaw** [comment]
`final Entry entry1 = args.entry;
`
args in entry1 is underlined and says Only static members can be accessed in initializers..

Only static members can be accessed in initializers. 
Following the logic of Dart and OOP, I think you should try something like:

```dart
  final EntryViewArguments args = Get.arguments;

  foo() {
    final Entry entry1 = args.entry;
  }
```

you have a class, in an argument, you assign a value to another that you will still receive. Right on the line below, you are trying to create an object with this value, without the object being inside a function, that's why the error. You need to initialize a class instance before you can use it. With the Get State Manager we have the onInit() method to help with this. You can obviously use the builders of your ViewModel class for this as well, but you definitely can't do something the way you're doing it, because EntryViewArguments is a class, and it needs to be initialized, and it violates the OOP rules, so the lint is warning you.

**Comment by Jethro87** [comment]
Thanks for your response.

I assumed because I was passing an instance of the class to Get as an argument, I would be able to access it as written above.

```
Get.toNamed(
      Routes.libraryView,
      arguments: LibraryViewArguments(fromEntryView: true),
    );
```

But I have managed to get it working by using the view model's constructor.

Thanks again.
