### ISSUE TITLE
Support for adding custom overlays

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#126]
**Is your feature request related to a problem? Please describe.**
I want to add a black transparent layer over the screen with a circular process indication. But I didn't see that Get had any API for that.

I was experimenting with the following controller. It works but needs the BuildContext. I tried using Get's context but this did not seem to work and give a null reference exception on overlaystate when trying to insert the entry.

```
class OverlayController extends GetController {
  static OverlayController get to => Get.find();
  bool _isShowing = false;
  OverlayEntry _overlayEntry;

  bool get isShowing => _isShowing;

  show(BuildContext context, Widget overlay) {
    if(_overlayEntry != null)
      return;
    final OverlayState overlayState = Overlay.of(context);
    _overlayEntry = OverlayEntry(
      builder: (context) => overlay,
    );
    //Get.context doesn't work here and throws an error that overlaystate is null
    //Get.overlay context work here and throws an error that overlaystate is null
    overlayState.insert(_overlayEntry);
    _isShowing = true;
    update(this);
    print('insert overlay');
  }

  void remove() {
    if (_overlayEntry == null) return;

    _overlayEntry.remove();
    _isShowing = false;
    update(this);
    print('remove overlay');
  }

  static Widget loadingOverlay() {
    return AbsorbPointer(
      child: Container(
        width: Get.context.size.width,
        height: Get.context.size.height,
        color: Colors.black.withOpacity(0.8),
        child: Center(
          child: PlatformCircularProgressIndicator(),
        ),
      ),
    );
  }
}
```

**Describe the solution you'd like**
I would like to be able to insert / remove any overlay widget from anywhere in my app.

**Comment by jonataslaw** [comment]
Sorry, but I think you crossed the line that I would not recommend you to cross.
The idea of ​​Get is precisely to separate the View from the business logic, and sending a widget by parameter or inserting it into the controller goes against the scope of the project.
I understand that there is an interest in adding and removing Overlays dynamically, I myself have already thought about doing something similar in a project, and I came to the conclusion that the overlay widget must really be in the widget tree, for reasons of application security (all stack of the Flutter is built on top of an overlay widget, manipulating the state of an overlay outside the tree, can cause unwanted effects), and for reasons of design patterns (a widget must always be in the widget tree, even when opening dialogs , I create a widget for the dialog, and just call it from the controller with a Get.dialog, and I don't insert the entire dialog widget into the controller. This can make your project unreadable for another dev). Unfortunately I will have to close this issue, because I have no plans to make this possible, as it goes against the scope of Get.

**Comment by brightchip** [comment]
Is there a solution now ? How did you create an overlay or stack above the entire App ? I'd like create a YouTube like floating widget ( an Application level Pip )

**Comment by gOzaru** [comment]
@brightchip @duck-dev-go 
I think you guys need to learn about persistence widget. 
Please search it over the google for that.
There are many ways to implement it. 

Oh yeah,
if you are using GetX in persistence widget to show any of snackbar and dialog, you won't get any error at all. I have tested it. The only problem is if you want to show those basic widgets (snackbar and dialog from Flutter) on persistent widget. It will give an error which you cannot fix, unless you use GetX snackbar and dialogs, or a modified GetX snackbar like what I am working on.
