### ISSUE TITLE
Use Logger for Logs

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/get#129]
![image](https://user-images.githubusercontent.com/48252841/82598778-0c815b00-9ba3-11ea-9a21-67d7c9e7169d.png)
Logs could be a lot prettier if you used [logger](https://pub.dev/packages/logger).
Also thanks for the amazing plugin.

**Comment by Prn-Ice** [comment]
![image](https://user-images.githubusercontent.com/48252841/82603481-a7c9fe80-9baa-11ea-9b8a-d1ec3f828e37.png)
Still, on that note, how can I tell if a route is replaced, I'm currently routing using the routing callback and can't find any checks for that, is it possible.

**Comment by jonataslaw** [comment]
I think you might be more interested in creating a navigatorObserver for what you're trying to do. Just copy this class:

```dart
class CustomObserver extends NavigatorObserver {
  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    if ('${route?.settings?.name}' == 'snackbar') {
      if (Get.isLogEnable) print("[OPEN SNACKBAR] ${route?.settings?.name}");
    } else if ('${route?.settings?.name}' == 'bottomsheet') {
      if (Get.isLogEnable) print("[OPEN BOTTOMSHEET] ${route?.settings?.name}");
    } else if ('${route?.settings?.name}' == 'dialog') {
      if (Get.isLogEnable) print("[OPEN DIALOG] ${route?.settings?.name}");
    } else {
      if (Get.isLogEnable) print("[GOING TO ROUTE] ${route?.settings?.name}");
    }
  }

  @override
  void didPop(Route route, Route previousRoute) {
    super.didPop(route, previousRoute);

    if ('${route?.settings?.name}' == 'snackbar') {
      if (Get.isLogEnable) print("[CLOSE SNACKBAR] ${route?.settings?.name}");
    } else if ('${route?.settings?.name}' == 'bottomsheet') {
      if (Get.isLogEnable)
        print("[CLOSE BOTTOMSHEET] ${route?.settings?.name}");
    } else if ('${route?.settings?.name}' == 'dialog') {
      if (Get.isLogEnable) print("[CLOSE DIALOG] ${route?.settings?.name}");
    } else if ('${route?.settings?.name}' == 'snackbar') {
      if (Get.isLogEnable) print("[CLOSE SNACKBAR] ${route?.settings?.name}");
    } else {
      if (Get.isLogEnable) print("[BACK ROUTE] ${route?.settings?.name}");
    }
  }

  @override
  void didReplace({Route newRoute, Route oldRoute}) {
    super.didReplace(newRoute: newRoute, oldRoute: oldRoute);
    if (Get.isLogEnable) print("[REPLACE ROUTE] ${oldRoute?.settings?.name}");
    if (Get.isLogEnable) print("[NEW ROUTE] ${newRoute?.settings?.name}");
  }

  @override
  void didRemove(Route route, Route previousRoute) {
    super.didRemove(route, previousRoute);
    if (Get.isLogEnable) print("[REMOVING ROUTE] ${route?.settings?.name}");
  }
}

```

and Add on your GetMaterialApp:

```dart
GetMaterialApp(
  navigatorObservers: [CustomObserver()],
```

I think this package is amazing, but unfortunately adding an external package goes against Get's philosophy.
We try to keep the package as light as possible, and without any third party solutions, so that it is a light, stable, and ready to use lib.
This does not rule out the possibility of creating an "add-on" in the future including code generators, beautiful logs (like these), but for now, we are focused on performance, stability, and the addition of new features.

If you encounter any other problems, do not hesitate to open another issue.

**Comment by Prn-Ice** [comment]
Thanks a lot.
