### ISSUE TITLE
Routes keep existing when rebuilding a child widget

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#136]
**Describe the bug**
If I rebuild a child widget, the routes keep existing.

**To Reproduce**
If you have a root widget that has a builder and you rebuild that builder all the pages that were routed to stay in existence

I have this root widget which has a AuthenticationController that will rebuild when the user get's deleted for example. Once this happens my signup page get's built but all the routes that have been navigated to keep existing which causes problems.

```
  @override
  Widget build(BuildContext context) {
    return GetBuilder<PreferencesController>(
      init: PreferencesController(),
      builder: (preferencesController) {
        if (preferencesController.state != LoadingState.loaded) return PlatformCircularProgressIndicator();
        return GetBuilder<OverlayController>(
          init: OverlayController(),
          builder: (overlayController) => GetBuilder<AuthenticationController>(
            init: FirebaseAuthenticationController(),
            builder: (authenticationController) => GetBuilder<GetFutureController<void>>(
              init: GetFutureController(() => Future<void>.delayed(Duration(seconds: 2))),
              builder: (GetFutureController<void> delayController) => GetBuilder<ConnectionController>(
                init: ConnectionController(),
                builder: (connectionController) {
                  if (delayController.snapshot.connectionState != ConnectionState.done ||
                      connectionController.state == ConnectionStatus.uninitialized) return TheSplashPage();
                  if (connectionController.state == ConnectionStatus.none) return TheDisconnectedPage();
                  if(authenticationController.state != AuthenticationState.authenticated)
                  {
                    print('TheRootPage unauthenticated: ${authenticationController.state}');
                    return TheSignUpPage.create(context);
                  }
                    
                  print('TheRootPage authenticated: ${authenticationController.state}');
                  return TheAuthenticatedApp();
                },
              ),
            ),
          ),
        );
      },
    );
  }
```

**Expected behavior**
I expect all the routes to be close

**Flutter Version:**
1.17

**Get Version:**
get: ^2.5.6

**Describe on which device you found the bug:**
Android Simulator

**Comment by jonataslaw** [comment]
This is an issue that we only learn when we are facing a real case, like yours.
What is the difference between setState and dispose? This is a question that almost all Flutter programmers know how to answer, but they only realize this real difference in real situations, like yours.
setState only changes the state of your children, the disposite is called not when the state changes, but when that class has been removed from the tree.
Within an AnythingBuilder() widget, the state of the widget can change, but nothing is displayed:
```dart
if (a = 1) {
return A;
} else if (a = 2) {
return B.
} else {
return C;
}
```
when you do this, you are conditioning a return to a change of state (changing the state of 'a') and switching between A, B and C will not provide any of the other options, after all, it is a "setState", and setState cannot call a disposed method.

I'm not a big fan of inserting navigation logic into builder methods, because the documentation says that they should be pure and only receive widgets.
In my applications I usually create a splashScreen to do all of these tasks, and use it as a starting route. I also initialize a controller on it manually, and remove it with Get.delete at "logout", and call the same splashscreen after logging out to create another controller.

```dart
bool isLogged = false;

onInit() {
checkLogged();
}

checkLogged() async {
isLogged = await Anything.checkUserLogged();
navigate();
}

navigate() {
if (isLogged) {
Get.off (Home());
} else {
Get.off (Login());
}
}

```
Obviously you can use enums for the authentication status, this was just an example with a simple Boolean.

Themes I also usually load them on this screen, and you can insert everything on a single controller, or insert the instances of those other controllers into that "main" controller.
I believe that such an approach can even bring benefits in RAM consumption, and will allow code with less nested GetBuilders.

**Comment by MichaelOttink** [comment]
It get's kinda difficult with Firebase tho. Since it has a _onAuthChanged() which can fire at any moment and route you to a page. So when you put() a authentication controller it in your MainApp's onInit and then build the page it will fire during build a Get.off() to a page.

So what I did was I gave the AuthenticationController a initialize method and I call that in the builder of the splash page. But this feels really messy. So how am I supposed to trigger this controller to start checking for a AutStateChanged()

It get's really messy when trying to delete a account too. Because you call the FirebaseUser.delete() method and that will trigger the onAuthChanged() which will do a Get.off(). I'm not really sure how and when the Get.off() will update but it routes to TheSignUpPage and then throws an error for all the previous widgets because the controllers didn't get removed so all the streams are still intact.

Coming up with a good design is driving me crazy.
