### ISSUE TITLE
Running the "example" on iOS consumes much CPU while scrolling

### ISSUE THREAD

**Issue by Josemboa** [jonataslaw/get#137]
First, congratulation for your work and the well documented plugin.

I'm coming from Redux (I use flutter_redux) to manage my flutter state and I loved what I read on the Get documentation, Get seams to increase productivity. I tried to run the example using Xcode and I found it is using too much CPU when I scroll the List of the countries. Is it normal or I'm doing something wrong? I'm using flutter 1.18.0-11.1.pre and Get 2.6.1. Please see attached the screenshots.

<img width="1280" alt="Screen Shot 2020-05-25 at 10 39 37" src="https://user-images.githubusercontent.com/5972884/82795947-0b874c80-9e75-11ea-956f-cd8a7ea3dd3f.png">
<img width="1280" alt="Screen Shot 2020-05-25 at 10 39 43" src="https://user-images.githubusercontent.com/5972884/82795956-0d511000-9e75-11ea-8fc5-ca1dbb40abbe.png">
<img width="1280" alt="Screen Shot 2020-05-25 at 10 39 32" src="https://user-images.githubusercontent.com/5972884/82795935-05916b80-9e75-11ea-8b63-9008b8cea322.png">

**Comment by jonataslaw** [comment]
Hi, thanks for opening this issue.
CPU usage is high due to blur, and the absence of an image cache plugin, this is not related to "state management" (The state manager only applies on page 1 in the http request, all other pages only use the previous data and without changing the state.), after all, the example uses GetBuilder, which updates the state in blocks, making it logically the least CPU-consuming state manager for not having any computational logic involved.

**Comment by Josemboa** [comment]
Thank you. I'll close this issue.
