### ISSUE TITLE
Unusual keyboard behavior with Get.bottomSheet

### ISSUE THREAD

**Issue by Prn-Ice** [jonataslaw/get#138]
The keyboard displays above the bottom sheet when I use `Get.bottomSheet`, but it works ok with the traditional `showBottomSheet` call.

![Screen record from 2020-05-25 21 04 33](https://user-images.githubusercontent.com/48252841/82841162-f6d6a300-9ecc-11ea-9f74-dbf371512c94.gif)

Code:
``` dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            _FlatButton()
          ],
        ),
      ),
    );
  }
}

class _FlatButton extends StatelessWidget {
  const _FlatButton({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FlatButton(
      onPressed: () {
        showBottomSheet(
          context: context,
          builder: (_) => Container(
            padding: EdgeInsets.only(
              bottom: Get.mediaQuery.viewInsets.bottom,
            ),
            height: 200,
            color: Colors.red,
            child: TextField(),
          ),
        );
      },
      child: Text('Push Me'),
    );
  }
}
```

**Comment by jonataslaw** [comment]
Flutter has a problem where the bottomsheet does not respect safeArea. To fix this in an issue, I ended up removing the bottom padding, which solves the previous problem, but apparently creates another one (thanks for reporting this, the behavior doesn't happen on most devices, and I wouldn't notice it).
I think I'll go back to using Flutter's bottomSheet as a base (which will eliminate some 150 lines of code from that lib's bottomSheet), and I will redirect the previous issue to Flutter, since issues related to safeArea are completely beyond the scope of this lib.
I could work on a PR on this, most likely adding just a padding upwards would also solve the problem, but lately I don't have any time for that, my 3 hours of free time left to me is just to update this lib, and help the community on stackoverflow and forums on social networks.
I will do a rollback now that will fix this.

**Comment by Prn-Ice** [comment]
Thanks for responding so quickly, I'll look forward to the update.

**Comment by jonataslaw** [comment]
Changing plans, the Flutter showBottomSheet is very archaic, now that I realized why I created another implementation, just as I did with the snackbars, despite their raw API being powerful, the showBottomsheet method seems like an evil joke like, you don’t have the ability to name bottomSheets or use any feature from 1.17, unlike dialogs that allow this by default, and these things are essential for GetObserver, and for callbacks like Get.isBottomSheetOpen, so what I can do is use their raw API, and make some implementations on top.

Let me ask, if you use:

showModalBottomSheet()
instead of showBottomSheet()

Does Flutter the problem occur?

Because if the problem also occurs with showModal, I will have no alternative but to get my hands dirty.

**Comment by Prn-Ice** [comment]
Just checked, the problem does occur with showModalBottomSheet

**Comment by jonataslaw** [comment]
> Just checked, the problem does occur with showModalBottomSheet

What version of Flutter are you using? I will need to know this to open an issue there, before starting a PR.

**Comment by Prn-Ice** [comment]
``` sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_NG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jonataslaw** [comment]
Thanks!

**Comment by jonataslaw** [comment]
Related to issue https://github.com/flutter/flutter/issues/18564

**Comment by jonataslaw** [comment]
Apparently they forgot to insert a Padding with viewInsets to prevent the keyboard from overlapping the BottomSheet.
Fix on last version

**Comment by Prn-Ice** [comment]
I can confirm that it works as intended now, thanks for the amazing package again. Also cool new logo.
