### ISSUE TITLE
Business Logic (Question)

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#141]
The Controller, is this the place to write all business logic, or do you have Services, Repositories too?

**Comment by jonataslaw** [comment]
You can write anything as long as you extend DisposableInterface();


```dart
class CustomDio extends DisposableInterface{
Dio dio = Dio();

Future<Model> fetchUsers(){
   final response = dio.get("url"); 
   return Model.fromJson(response.data);
}

@override
 onClose{
  dio.close();
 }
}
```
on route:
```dart
'/': GetRoute(page: Home(), binding: HomeBinding())
```
on Binding:
```dart
class HomeBinding implements Bindings{
@override 
dependencies(){
Get.lazyPut<Controller>(()=>Controller());
Get.lazyPut<CustomDio>(CustomDio());

or 

Get.lazyPut<Controller>((){
                 CustomDio custom = Get.put(CustomDio());
                 return Controller(dio: custom);
});

or 

 Get.lazyPut<Controller>(()=> Controller(dio: CustomDio()));
 }
}
```

**Comment by jonataslaw** [comment]
Maybe I do a separation by classes just so that it is possible to configure things like:

Services: Services.keepAlive // Services.onRoute // Services.autoDisposable

But this will depend on the new route API, which will be able to arrange classes on onPop, and if you define a service in a binding and have marked Services.onRoute, when you pop in a screen that called that service, it will be taken from memory.

**Comment by stefandevo** [comment]
Okay this Binding stuff is very new I guess?

**Comment by jonataslaw** [comment]
> Okay this Binding stuff is very new I guess?

Yes, it is quite new, and follows a new way of doing things like state management. Instead of GetBuilder, GetX will have a function capable of rebuilding widgets like this:
obx(() => Text(controller.text)),

The bindings API is already quite secure, this obx which is highly experimental, I copied the idea of ​​something I saw on microsoft MAUI, and I liked it, but it’s a new, untested approach, and therefore not recommended for use in production, but those who like to venture out are very interesting.

And obviously for this to be completely stable, I will have to redo the routes API, which will be in charge of communicating pop, push, and routes removed from the stack to the dependency manager, which will do all the dependency injection and disposal work, the version 2.6 has already brought some progress in this regard, since now calling delete from a controller, it will first call the close method, only then to be removed from memory, completely preventing memory leakage. I tried to document a little of this, but it's worth a chapter in the "controllers lifecycle" part.
