### ISSUE TITLE
Duration of transition for Get.to()

### ISSUE THREAD

**Issue by domons** [jonataslaw/get#15]
Can I globally change time of fade transition? In GetRoute is parameter duration, but I don't know how used it without changes in library code. Is it possible?

**Comment by jonataslaw** [comment]
> Can I globally change time of fade transition? In GetRoute is parameter duration, but I don't know how used it without changes in library code. Is it possible?

It is not possible to globally define the duration of the transition, precisely because you can define different durations for each type of transition. However, it was added on 1.10.4 the possibility to define the duration on unnamed routes, example:

usage: Get.to(Home(), duration: Duration(seconds: 1));
