### ISSUE TITLE
RxController not reactive to enum changes

### ISSUE THREAD

**Issue by lotus-x** [jonataslaw/get#151]
**Describe the bug**
When changing a value of enum which stored in a RxController, GetX builder not reactive to that change. Is there anyway around to initialize enum in Controller? I have converted the enum to Rx object using .obs extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/43782734/83100715-302a3100-a0ce-11ea-854a-594474248500.png)
![image](https://user-images.githubusercontent.com/43782734/83100739-43d59780-a0ce-11ea-9a70-bcd6768081ad.png)

**Flutter Version:**
Flutter 1.17.1 • 2020-05-13 18:22 • f7a6a7906b • stable

**Get Version:**
2.6.3

**Comment by lotus-x** [comment]
Sorry I found whats happening,

GetX can't recognize that page variable is used by the children.
![image](https://user-images.githubusercontent.com/43782734/83101812-ceb79180-a0d0-11ea-85d0-b81b00a88e09.png)

But when it initialized at the beginning the builder is reactive to the changes
![image](https://user-images.githubusercontent.com/43782734/83101834-daa35380-a0d0-11ea-91c3-21ba305db7a6.png)

Is this an unexpected behavior or I'm missing something?

**Comment by jonataslaw** [comment]
This is expected, but not documented, behavior. As a rule, GetX reconstructs the exact child in the first descent position, and if you want it to advance one level, it will be necessary to insert the reactive variable right after the build method.
It turns out that the data delivery flow from the central pool to the variable, needs an intermediary, which in this case is a Get.obs, created in the GetX constructor, and deleted as soon as the child widget is rebuilt, delegating the responsibility to update the data to a StreamSubscription, which is very economical in RAM. The positive point of this approach is the economy of resources, the weak point is precisely this behavior.
I particularly find this a bit boring, and if I can find a way to change it without affecting the stability of the lib I will certainly do it, there is no guarantee that it will change, because I don't know of any callback similar to SchedulerBinding.instance.addPostFrameCallback capable of report building all the children of a widget, and maybe Flutter doesn't have an API available to test this, but I'll try to think of something, or document it as expected behavior if there really isn't a better way to do it.
I could store everything in maps, as MobX does, but I created GetX based on Streams just to save RAM, and instead of storing data, use Streams, because data from a stream doesn’t consume ram, it crosses the stream and disappears, so I'm really going to see what I can do about it.

**Comment by lotus-x** [comment]
Thanks for the quick reply..
Isn't it good to add method like update(this) in GetController to rebuild all child widgets using given RxController? It would be easy like in this cases in my opinion.

BTW I'm really happy about your goal and the vision of the library. I was using async redux after get rid of flutter redux and its middlewares but all the same. Too many code redundancy and lot of time take to do even simple thing. I found your library when i was finding for an alternative. Right now I'm converting my whole app to it. Keep work on what you like and stay away from toxic. Don't give up. I'm going to use your library in production even its in young age. Update the documentations too cuz it's hard to get familiar if someone didn't take a closer look. Happy coding!!!

**Comment by jonataslaw** [comment]
Well, I spent all night researching for this, and discovering that it will be difficult to create something of this level, and the problem is with Builders widgets and how Flutter works with them.
If you have 300 stateless widgets, GetX will rebuild it, no matter how many children there are. This is because a StatelessWidget is literally part of its parent structure.
If you have a StreamBuilder, LayoutBuilder, or AnyBuilder as a child, the compiler will move to the next line, and that builder will be built in another event, because it is a stateful that needs to create an element, and return a chain of widgets to it that is inside, but not part of your father, so you can reconstruct the children of an AnyBuilder, but you cannot change the text of a Text(), Text is not a Builder widget, so it is part of your father's structure, already Builder widgets are separate, and you can even rebuild them as with StreamBuilder, and I believe that Flutter does this separation to improve the build time of the tree.
This behavior happens not only with Get, I just tested MobX, and although they have not documented this, the same error occurs. This is more of a Flutter architecture, so I'll document this, I think it's important to make this information explicit, to avoid mistakes.

**Comment by lotus-x** [comment]
So you can add a feature like manually refresh the state of GetX using controller as I mentioned before to handle this kind of situations. Isn't it a good idea?

**Comment by jonataslaw** [comment]
Well, I think that might not be a good idea.
As described in the documentation, for multiple state control, GetBuilder's performance is higher, so in situations where manual control is necessary, a GetBuilder will be better than a GetX. GetX is aimed at individual and refined state control, so there are two options in this package.

**Comment by lotus-x** [comment]
But a whole new controller is required to GetBuilder 🙁
