### ISSUE TITLE
Way to use multiple controller properties in single GetX widget

### ISSUE THREAD

**Issue by lotus-x** [jonataslaw/get#159]
Is there a way to use properties from multiple controllers through one GetX widget.
For example,
There are two controllers, Controller1, Controller2
When using GetX<Controller1>(), i also want to get some properties from Controller2.
Is it okay to define Controller2.to.someProperty in Controller1 and use it in the GetX widget?
Would it reactive to Controller2 changes?

**Comment by jonataslaw** [comment]
As long as you have already initialized your controllers, you can use 1, 2 and up to 300 controllers in the same GetX without any problem.

**Comment by lotus-x** [comment]
Yeah, it's clear that I can use controllers like Controller.to or Get.find<Controller>().
But, is it reactive for changes in those controllers?

**Comment by jonataslaw** [comment]
Yes, the widget does not communicate with the controller, it just opens a StreamSubscription to hear the values of its direct children.
The type in GetX is just to make the job easier, because typing Get.find <Controller> () can be simplified with a ctl.value.
But that does not mean that there was any relationship between that widget and the Controller in the case of GetX, because GetBuilder does, it has a direct relationship with the Controller that he listens to.

**Comment by lotus-x** [comment]
Thanks mate, really appreciating your work ❤
