### ISSUE TITLE
What can be "above" GetMaterialApp?

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#160]
I read through the questions/issues about GetMaterialApp being absolute the first thing in runApp and possible issue involved (memory etc) when you do wrap it.

However, some packages require to wrap the MateriaApp (and thus the GetMaterialApp). 
Mostly packages that needs control over the complete widget tree or bug/analytics trackers.
Some packages:
- https://pub.dev/packages/wiredash
- https://pub.dev/packages/version_banner
- https://pub.dev/packages/device_preview

etc.
Is it still OK to place these "widgets" on top of GetMaterialApp?

Thanks for your guidance.

**Comment by jonataslaw** [comment]
> I read through the questions/issues about GetMaterialApp being absolute the first thing in runApp and possible issue involved (memory etc) when you do wrap it.
> 
> However, some packages require to wrap the MateriaApp (and thus the GetMaterialApp).
> Mostly packages that needs control over the complete widget tree or bug/analytics trackers.
> Some packages:
> 
> * https://pub.dev/packages/wiredash
> * https://pub.dev/packages/version_banner
> * https://pub.dev/packages/device_preview
> 
> etc.
> Is it still OK to place these "widgets" on top of GetMaterialApp?
> 
> Thanks for your guidance.

As answered in another question, this is likely to change.
The need for this is commonplace, it is just for a feature that has not even been documented, and has no significant usage fees called "restartApp()".
The idea was to assign a new key to the materialApp in case it was necessary to reset the app, and assigning a parent to it would cause unwanted effects, not in the case of the libraries that you mentioned are normal Widgets, not WidgetBuilders, but if someone inserted it inside a StreamBuilder for example, would certainly cause duplication of keys.

I will remove this function in the next update, and remove this requirement because there are more points against that. If someone wants this function, just create a Controller with a key and assign it to GetMaterialApp and update the key. It is not something that changes much. Anyway, it is an unnecessary feature that gets Get blocked.

**Comment by stefandevo** [comment]
Thanks for the clarification!
