### ISSUE TITLE
Register Future result in Instance Manager

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#172]
I am trying to register `SharedPrefecerences` instance in the Get instance manager for later use.

```
    Get.lazyPut<SharedPreferences>(() async {
      return await SharedPreferences.getInstance();
    });
```

I would expect that SharedPreferences as an instance is now in the instance (first time we try to get it).

I try to get it:

```
  final prefs = Get.find<SharedPreferences>();
```

Error:

**flutter: type 'Future<SharedPreferences>' is not a subtype of type 'SharedPreferences' in type cast**

I would expect by returning `await SharedPreferences.getInstance()` I registered the `SharedPreferences` type.

Any idea?

**Comment by jonataslaw** [comment]
final prefs = await Get.find<SharedPreferences>();

I usually do this:
But I will think about supporting asynchronous operations in the future

**Comment by jonataslaw** [comment]
Initially, it is impossible with Dart to register an asynchronous function and obtain it synchronously.
So
`Get.lazyPut <SharedPreferences> (() async`
there's no way to deliver
`final prefs = Get.find <SharedPreferences> ();`

Because Future to be converted into an object, it needs to undergo a synchronous operation. If it is done in lazyPut, extracting it from the function would call the instance (it would no longer be lazy), and then call in find, find would have to have an "await" before, and be an asynchronous operation.
I thought about creating a getAsync to solve this, but get_it inserted in the documentation that asynchronous calls could only be obtained with getAsync() and yet people open issues every day about errors related to this.
In Get this could lead people to register controllers with Get.lazyPutAsync, and when she tried to get the instance in GetBuilder/GetX/ she would have an exception, and that would cause a flood of unnecessary issues.
So the safest alternative I found to do this was to add an asynchronous method similar to Get.put, so when registering it is possible to transform Future into an object and register it, so I included Get.putAsync () in the latest version, but even this method can have side effects. If registered in a Bindings, for example, I believe it will not start in time for the build method to be called. Anyway, about Get.findAsync () that would allow a Get.lazyPutAsync, I think it is better to mature this idea and see if there is a safer way to do this.

**Comment by stefandevo** [comment]
Understand it completely. Do not put the library at risk for this. Add it to readme to do a await Get.find as you suggested first for this. Otherwise I now created the instance first and added via .put

**Comment by jonataslaw** [comment]
Added on lastest version

**Comment by FallenRiteMonk** [comment]
@jonataslaw how would I go about using the putAsync in a binding? I would need the sharedpreferences in a controller that is included in the initialbinding of my app!
