### ISSUE TITLE
Usage of Bindings

### ISSUE THREAD

**Issue by stefandevo** [jonataslaw/get#174]
What are the benefits of using Bindings?
If I understand it correctly; you do not have to use the init property on the GetX for example, but instead you need to create a new class?
Of course you could Get.put more than one controller/services in the Bindings, but if you have 1-1 Widget - Controller, what are the benefits?

**Comment by jonataslaw** [comment]
Dependency injection is easier.
Imagine a hypothetical situation that you want to start an Api consultation service, and you only want it to enter memory when your controller needs it.
In addition, you want that when the controller is deployed, your service will be as well and you need to close the Dio/Http client before the dependency is deleted.

You can do this with init as well, but it would be much more complicated to manage that, because you would have to initialize your Service in onInit maybe, or you need it to be initialized before. A lot of people start everything up on the main, and that for big projects is bad, because it causes a lot of disorganization.

If init solves the problem, there is no danger in using it, but there will be cases where a single screen can use more than 1 controller, and each of these uses a different service. You can initialize them all in the Binding class, and in your controller you can retrieve the same instance of your service with `Service service = Get.find();` sharing the same service for all Controllers registered in the same binding (I think this is the most important argument here).

In addition, there is no way to register services in the widget init, so if you register them before, they can stay in memory forever,
If you register with Bindings, it will be removed as soon as it is no longer needed.

Another advantage is that you can use Obx using Bindings, so instead of using:

```dart
GetX<Controller>(
 builder: (Controller controller) {
 return Text(controller.text);
 }
);
```

You can simply do this:

`Obx(()=> Text(controller.text));`

or that:

`Obx(()=> Text(Get.find<Controller>().text));`

or that:

`Obx(()=> Text(Controller.to.text));`

This will still allow you to listen and change variábles within other builder functions, without having to encapsulate the entire widgets by adding only  `=> obx(()` on builder funcion

```dart
StreamBuilder<Object>( // or listview.builder or any Builder widget
              stream: mock.stream,
              builder: (context, snapshot) => obx(() {
                return Container();
              }),
            ),

```

**Comment by stefandevo** [comment]
So `Obx` is preferred? If you have 3 properties on the Controller, would you prefer to use 3x times the `Obx(()=> Text(Get.find<Controller>().text1));`, `Obx(()=> Text(Get.find<Controller>().text2));`, `Obx(()=> Text(Get.find<Controller>().text2));` or is the overhead of using the `Get.find` 3x times too big?

With `Obx(()=> Text(controller.text));` where is `controller` defined?

**Comment by jonataslaw** [comment]
Get.find() has some computational logic involved. It is not expensive, it only makes two queries on two Maps, but certainly minimizing its use will avoid a series of validations such as "Is this controller already in memory?" "Is there a factory registered for me to generate an instance if it is not in memory?" and it will save a few CPU cycles.
This depends a lot on the occasion, but if you have 20 Get.find<Controller>() .object I would strongly recommend you do something like:
Object object = Get.find<Controller>().object;

If you have 50 variables on the same controller, I recommend you do something like:
Controller ct = Get.find();

ct.object1;
ct.object2;
ct.object50;

The impact of this is very low, the difference should not be noticeable, but if you want to be minimalist, using Get.find() only when necessary can be better.

note:
Controller ct = Get.find(); it will increase the memory used by 0, because however it goes against common sense, this is not creating a new object, but accessing an already allocated object.

void main() {
  test('test', () {
    Get.put<Controller>(Controller());
    Controller ct1 = Get.find();
    Controller ct2 = Get.find();
    expect(ct1.hashCode, ct2.hashCode);
  });
}
ct1 and ct2 don't even appear and the number of "Controller" instances is marked as 1 in the Dart inspect, so you can use this without fear, you can have 1 billion of these, you won't be increasing your RAM usage.

**Comment by TJMusiitwa** [comment]
I just came into this same issue right about now using both firebase auth to register the user, then when the future completes, use firestore to add more user information.
I have done it in a hacky way but I will update to use Bindings when I can better understand it.
Or can you nest controllers sort of like how Provider allows you to nest providers or go the route of MultiProviders?

**Comment by jonataslaw** [comment]
Added on documentation
