### ISSUE TITLE
Possibly expose buildTransitions()

### ISSUE THREAD

**Issue by 1N50MN14** [jonataslaw/get#183]
hey @jonataslaw many thanks for get!

I switched over to using it today, in a web app actually, and the only thing that I'm missing is either `fadeIn` (or even no transition at all).  I saw in the code you have `customTransition` declared somewhere but I didn't quite get where or how it's used.

Any tips on how I can get this working would be appreciated.

Thanks

**Comment by jonataslaw** [comment]
I am thinking of a safe way to do this. The biggest problem with this is that Get's transitions are safe and tested. Creating a custom transition can bring problems to iOS.

There are things that are not mandatory for perfect functioning, like this:

```dart
_CupertinoBackGestureDetector<T>(
                        enabledCallback: () => _isPopGestureEnabled<T>(route),
                        onStartPopGesture: () => _startPopGesture<T>(route),
                        child: child)
```

And I would have to leave the public class in order to be able to use this in a custom class.

I thought about maybe creating a standard class, where you can change the animation and the transition effect, and play these elements within buildTransitions.

**Comment by jonataslaw** [comment]
If you don't want a transition, you can change the transition duration to Duration.zero.
About custom transitions, this is something I need to think about how to do it safely, there would be no problem with the web, but iOS devices are very sensitive to this, and any custom transition can cause a black band in the background, or cancel the popGesture.

**Comment by 1N50MN14** [comment]
Yes I understand. The problem with `Duration.zero` is that it doesn't really result in an instant transition as the route needs wait for the child page to build, as such it feels laggy. A simple a `FadeTransition` would solve this (I guess it'd work on the iOS as well).  

Another approach would be to expose something similar to `pageTransitionsTheme` 
```dart
 pageTransitionsTheme: const PageTransitionsTheme
(
    builders: <TargetPlatform, PageTransitionsBuilder>{
      TargetPlatform.android: ZoomPageTransitionsBuilder(),
     },
)
```

`TargetPlatform` does not expose `Web`, but Get does: `GetPlatform.isAndroid/isIOS/isWeb`, as such a similar API could be exposed and if a user explicitly chooses to override the default iOS transition for whatever reason, then sure.
