### ISSUE TITLE
Whats the difference of the simple state manager from the reactive one?

### ISSUE THREAD

**Issue by Nipodemos** [jonataslaw/get#200]
I read that the simple one merge the state of all "rebuild-able" parts of the screen into one, and when it is called the `update()` all states will update. And GetX will make it separately, defining a unique ID for each state.

But that's all? i mean, is there any other significant difference? Because to me if this is the only difference i think maybe is not worthy it do keep the simple one, since the GetX can too update several places at the same time, given they are all the same information (as you said on the shopping cart example)

so why bother have two state managers?

**Comment by jonataslaw** [comment]
I added this to the 2.11 readme.
It really lacked a clear explanation of that. But basically, SimpleStateManager is the simplest in state management, especially in the latest updates that it stopped storing State in a Map in order to update widgets. In the last benchmark in AOT it is simply lighter than a FlatButton, literally, it does not store anything that can impact the use of ram, even though there are 700 of them.
GetX, on the other hand, is all the most sophisticated in state management. I literally took all the positives and negatives from all the state managers to shape it. I liked the Provider Selector, I placed it, I liked the idea of ​​modifying BLoC streams, I placed it, I liked the absence of MobX typing, I placed it, I removed the unnecessary BLoC boilerplate, I removed the need to use context to access objects like the Provider, and I did everything so that the use of code generators like mobx was unnecessary. GetX is very good for large applications, but GetBuider is still great for smaller applications that want to spend minimal, and you can use both in the same project as well.
GetX will consume a little more RAM than GetBuilder, more so much less than MobX and Bloc

**Comment by Nipodemos** [comment]
ok i understand.
Thank you for explaining 😄
