### ISSUE TITLE
Benchmarks do not appear to be accurate

### ISSUE THREAD

**Issue by felangel** [jonataslaw/get#243]
Hi 👋 

I opened https://github.com/jonataslaw/benchmarks/issues/5 on the benchmarks repo because after profiling the bloc library vs get in particular the memory usage I observed and the memory usage documented are not consistent.

**Total Memory Consumption:**
bloc library: ~544 bytes
get: ~960 bytes

**Get**
<img width="1138" alt="get" src="https://user-images.githubusercontent.com/8855632/84623323-a5567e00-aea4-11ea-9998-63cb3e7edf72.png">

**Bloc Library**
<img width="1123" alt="bloc-library" src="https://user-images.githubusercontent.com/8855632/84623324-a7204180-aea4-11ea-9228-43de5dbd2816.png">

I haven't profiled the others but based on my findings with the bloc library which is represented as being the worst in terms of memory usage according to the [benchmark graphic](https://github.com/jonataslaw/benchmarks/blob/df0d9ba0d2c8ce429e6a89c25aa3301f88f82847/benchmark.png) I have some doubts about the validity of the remaining metrics.

I would ask that you please avoid posting this type of information unless you are confident that it is accurate and unbiased because it is otherwise misleading and paints other state management libraries in a negative light which isn't fair to the community.

I would really appreciate it if you would please update your benchmarks and documentation and in the future I would highly recommend reaching out to the package maintainers and working with them on the benchmarks to make things as accurate and unbiased as possible, thanks 🙏

**Comment by jonataslaw** [comment]
The Get class is not even compiled when the project does not use routes.
GetMaterialController? Routing? is it serious? Haha.
Well, I accepted your pull, and redid the benchmarks, and you can clone, and do the tests yourself like anyone else.
However, you should run the project equally for everyone, it is not right to run the default project for you, and another one using all the dozens of Get features because this is not fair, however, I believe it was a mistake in which you used the GetMaterialApp (which injects routes, snackbars, dialogs, bottomsheets, mediaUtils, platforms and a dozen more resources) when wanting to compare state managers.

Here is the RAM consumption of your lib, with its changes in the repository:

![flutterbloc](https://user-images.githubusercontent.com/35742643/84630585-8c5cc580-aec2-11ea-9e4f-162a9b60696e.png)

Here is the RAM consumption of GetX

![getx](https://user-images.githubusercontent.com/35742643/84630628-9aaae180-aec2-11ea-809a-a44133f0cd20.png)

And GetBuilder

![get](https://user-images.githubusercontent.com/35742643/84630672-a8f8fd80-aec2-11ea-8c55-5919743aab8a.png)

With your changes your lib has improved a lot, congratulations, and I will have to update the Ranking, which now appears with another lib being the one that consumes the most RAM, but Get continues to follow with a considerable advantage in relation to the others, even because the focus of Get is this one, and it will be difficult to compete with a totally StatelessWidget lib, you will always need a device, because everything is on the UI side, while Get transfers all this to the controllers. This does not mean that it is a better approach, it is a matter of personal taste, it just makes Get win in one aspect, but there are others to consider, such as documentation and maturity (that yours is the best), native integration (Provider uses everything that Native Flutter has it while Get is not at all orthodox), and for that we have more than 50 state managers at pub.dev, for each person to use the one they like best.

**Comment by rrousselGit** [comment]
There is something wrong with these numbers.

We are talking about a difference of 26kb between get and bloc in your pictures.
That's 26 thousand booleans. An instance of  `ItemBloc` weight 48 bytes. 26kb  is enough to instantiate more than 540 of the Bloc.

That doesn't add up.

**Comment by orestesgaolin** [comment]
> GetMaterialController? Routing? is it serious? Haha.

I find this kind of statements very rude and unhealthy for the general audience reading these discussions. As a library maintainer please make sure that your language is conveying the proper message and does not make other open source contributors feel attacked. 

I suspect that many beginners will fall for this kind of attitude, because they may feel better "as the ones using the only proper library". Probably there are some advantages of using get instead of other libraries but I can guarantee that there are some areas where even using _old_ ScopedModel would be a better choice. It's how computer science works that in vast majority of discussions there's no single best solution.

Forgive me if you feel bad after reading my message. I don't want to discourage you from doing great job as OSS contributor, but just want to let you know that this kind of responses may lead to separation in the community. Take care and I hope to see improvements in the benchmark methodology. This might be a beginning of some great tool if developed with fairness and clarity in mind.

**Comment by RollyPeres** [comment]
> However, you should run the project equally for everyone

You should have given this advice to yourself in the first place. 

It's great to strive to be the best, but shedding dark light on other's great work is not the way to go. I find your approach and attitude to be really disrespectful towards guys like @felangel and @rrousselGit who've done some amazing work for the flutter community,

**Comment by jonataslaw** [comment]
I respect and admire the work Remi and Felix have done so far. Both were pioneers in creating state management and dependency injection tools, and this was of great value to the community.
In many places, even in the documentation, I explain that Get is not for everyone, and I highlight points from other state managers that must be taken into account.
I didn't want to send benchmarks, that was Remi's idea. I definitely didn't think that was ethical, but Remi said he took responsibility.
There are many points when choosing a state management, ranging from maturity (flutter_bloc and provider are very mature), to personal taste. Get was developed in order to use the lowest level of resources possible, and there is no way for other state managers to try to compete with something that has been studied for 2 years to have the most economical approach possible, just as there is no way for Get to compete with maturity. Provider and Bloc, which has 100% coverage and has been in the market for years. Each could focus on their strengths instead of creating that clash.
I have always treated Felix and Remi with as much respect as possible. This Felix issue seemed unfair to me, I didn't like the way he approached it, and the words he used, calling it a farce test, and creating a manipulated benchmark to try to convince someone of a point. He edited the issue less aggressively, but that doesn’t change what I saw, nor does it change the fact that he navigated routes and used everything that Get could offer to inflate the use of RAM (this is not me, look at GetMaterialController and Routing in memory, this is only used when routes are used, without routes these services are not even started).
I opened the repository for the creators of the libs to modify in the way that best used their lib. I accepted a PR from Remi and another from Felix, and tried to act with as much transparency and impartiality as possible, not least because I don't need to prove a point.
Finally, the benchmarks are open, anyone can clone and reproduce the tests, as long as they do not manipulate them, because using GetMaterialApp and navigating routes in a state management benchmark is not a legal attitude, and I even softened it up. that he could have done it by accident, because he didn't want to be harsh.
Finally, English is not my native language, so if something seemed rude, it was not my intention, and I apologize, just as I would like to hear them. I find this whole mess very unnecessary, and it shouldn't even have started. I just wanted a little more respect with my work too, I dedicated days of my time to deliver something that would make a difference for the community, and I don't need to take offense to try to prove a point. Nobody gets anything from opensource, I get nothing from maintaining this project, and this plot to depreciate my work just divides the community more.
As I said in the readme, Get is not the enemy of any state manager, not least because it is not just a state manager, it is a microframework that you can use in conjunction with other solutions or in a pure way. Stop this mess, please.

**Comment by rrousselGit** [comment]
Felix didn't manipulate anything.

I ran the same tests and got the same snapshot before. That's the reason why I mentioned Navigation in my tree-shaking comment: https://github.com/jonataslaw/get/issues/238#issuecomment-643800283
As when I ran the benchmark myself, I saw the Route objects in memory too.

**Comment by rrousselGit** [comment]
>  This Felix issue seemed unfair to me, I didn't like the way he approached it, and the words he used, calling it a farce test,

The history if the edits on his post is available. He didn't say "farce test".

**Comment by rrousselGit** [comment]
As a comeback to the benchmark manipulation:

The problem is part of the version  2.12.4 

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get: 2.12.4
  ...
```

If you run the benchmarks without changes in 2.12.4, you'll see GetMaterialApp and other things in memory.
So here's the proof that he didn't manipulate anything.

**Comment by jonataslaw** [comment]
> As a comeback to the benchmark manipulation:
> 
> The problem is part of the version 2.12.4
> 
> ```yaml
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^0.1.2
>   get: 2.12.4
>   ...
> ```
> 
> If you run the benchmarks without changes in 2.12.4, you'll see GetMaterialApp and other things in memory.
> So here's the proof that he didn't manipulate anything.

Thanks for clarifying this, but this version didn't even stay in the pub for 20 minutes (And when I uploaded the benchmark repository, that version was already legacy), and the benchmark is marked "^", that is, the last available version that would be downloaded, and not the exact version, but he may have changed manually by accident, or the pub get delivered an older version, but that doesn't matter now.

Anyway, I would like this to be definitely resolved, fights don't help the community at all.

**Comment by orestesgaolin** [comment]
> Anyway, I would like this to be definitely resolved, fights don't help the community at all.

As a quick recommendation I can suggest you to read your message before sending it _from the receiving point of view_. Sometimes we unintentionally use words that can be considered rude and they just stick to us even though we didn't mean it. I know it may be difficult in "live" and "heated" discussions, but we are all used to asynchronous tasks so few extra minutes between responses shouldn't hurt us. I found this few years ago and have been trying to empathize with other participants of online discussions since then. One silly sentence between long technical comment can ruin the whole message, so the loss of time and nerves can be even more significant. Peace ✌️

**Comment by jonataslaw** [comment]
I appreciate your advice, thank you. I am ending this, because there is no reason to continue with this discussion, since the problem originated from the use of an old version, and the issue is already being discussed more deeply in another topic.
I hope the spirits will calm down, because nobody has anything to gain from fights.

**Comment by dasaintgray** [comment]
As a user of Get library, I really admire your time and effort in producing this excellent library for the community. Once again, thank you so much.

**Comment by bigbott** [comment]
I am so happy, that I finally found the root of the GetX controversy going everywhere. GetX is a great package!!!
