### ISSUE TITLE
Replace Get.off() with Get.close(pages.length-1)

### ISSUE THREAD

**Issue by michael-ottink** [jonataslaw/get#280]
Statemanagement.full and factory tend to have problems with using Get.offAll(). I have been using get.close(pageCount) instead and it works wonderfully. Could it be an idea to replace the offAll() api with the close()? Let me know what you think :)

**Comment by jonataslaw** [comment]
I think they are different APIs for different purposes, but nothing prevents you from using the close, if you know how many pages to close, just use it.

**Comment by michael-ottink** [comment]
Cool, is there any way to get the amount of pages without tracking it myself?

**Comment by jonataslaw** [comment]
One API you are turning pages, the other you are going to one and removing the others, because more than they look alike, they are different.
You can use the same api that I showed you in the other issue to do what you want:

 Get.until((route) => route.isFirst);

This will remove all of your pages and return you to the home page.
There are so many possibilities to do the same thing in different ways that I could spend an entire night here.
