### ISSUE TITLE
How to pass data thought routes? Like an ID...

### ISSUE THREAD

**Issue by darlantc** [jonataslaw/get#3]
Like:
`Get.toNamed("/article/:articleID");`

**Comment by jonataslaw** [comment]
> Like:
> `Get.toNamed("/article/:articleID");`

You can easily pass data between named routes using arguments. The implementation of named URL segments ": articleID" is nice, but for now not possible due to Dart limitations, version 2.6 will bring extensions, which is a kickoff for this to be possible. However, you can be sure that as soon as you can create this, I will.

While this is not possible, you can do the following:

Get.toNamed('/profile', arguments: {"user_id:"1"})

on Router class:

GetRoute(settings: settings, builder: (_) => Profile(data: settings.arguments));

on Profile class:
class Profile extends StatelessWidget{
final data;
(...)
