### ISSUE TITLE
Transition bug?

### ISSUE THREAD

**Issue by klaszlo8207** [jonataslaw/get#34]
When I call Get.to(..., transition.fade)

I see the off transition on the previous page rightToLeft with fade (but it will be fade OUT ONLY)

Any way to create a Transition.Nothing? (and/or transitionIn/transitionOut?)

I need to handle the in and out animations too.

Thanks

**Comment by jonataslaw** [comment]
> When I call Get.to(..., transition.fade)
> 
> I see the off transition on the previous page rightToLeft with fade (but it will be fade OUT ONLY)
> 
> Any way to create a Transition.Nothing? (and/or transitionIn/transitionOut?)
> 
> I need to handle the in and out animations too.
> 
> Thanks

I did not understand. Is this a bug report or a feature request?

**Comment by klaszlo8207** [comment]
It is both 😂

**Comment by jonataslaw** [comment]
Hi, Get uses native transitions to prevent breaches in app stores. This does not mean that you cannot casually use a different transition, but iOS manual analysis will reject your app if all transitions are different from Cupertino.
Android uses Transitions.fade which is the default for android, and on iOS it uses Transitions.cupertino.
You do not need to use Transitions.fade, unless you want this behavior on android and iOS, and your app will likely be rejected on the AppleStore if you do.
In view of this, there is no transition bug in Get, at least not in the latest version (1.12.0), if you use an old version, please update.
For custom transitions you will need to use named routes, and use a PageRouteBuilder (instead of GetRoute) for this.

**Comment by jonataslaw** [comment]
If you want to navigate without transitions, you can use duration: Duration (seconds: 0)

Since there is no bug description here, and no clear critical resource request, I am closing this.

**Comment by klaszlo8207** [comment]
Added Duration 0, but the BACK animation is STILL left to right with a 300 ms...

Please fix this!

**Comment by klaszlo8207** [comment]
I need transitionOn and transitionOff properties. 
It looks like you didn't handle the page OFF animation

**Comment by klaszlo8207** [comment]
Sorry this was the probleme

https://github.com/jonataslaw/get/issues/38

**Comment by jonataslaw** [comment]
The problem about Duration not working has been resolved. Was he related in any way to this issue?
After the last update the problem still persists?

**Comment by klaszlo8207** [comment]
In the latest version this was fixed, thanks
