### ISSUE TITLE
[PROPOSAL] middleware capabilities

### ISSUE THREAD

**Issue by rodrigobastosv** [jonataslaw/get#5]
I think it would be great if we could pass some kind of middleware to be executed on every page transition for example. The motivation is to be able to for examplo log to the console which route you are going to.

**Comment by jonataslaw** [comment]
I will leave this issue open because I am interested in implementing this.
I'm going to change a little bit about how things work in Get to allow this, and also implement route protection.

Currently, when accessing a route, it is immediately pushed, and I think maybe it would be better for the route to go through a validator first, and then go to the next route, and that's where your idea fits the new implementation.
I can't promise it will be this week, but I will do it.

**Comment by rodrigobastosv** [comment]
Great to hear that. With the growing of Flutter web Route Guarda Will bem absolutaly important. I'll vê following this issue to track the progress. Thanks!

**Comment by jonataslaw** [comment]
Added on 1.9.0
