### ISSUE TITLE
Rebuild last page

### ISSUE THREAD

**Issue by Senn3** [jonataslaw/get#52]
Hi,
first of all thank you very much for your great work on this package.
I'm using your package to improve the performance of my app by getting rid of the unnecessary build calls after several page switches.
Unfortunately, this also has the consequence that the page to which you switch when the back button is pressed is not reloaded.

E.g. if we got the following path: A --> B --> C. If the user goes back from C to B, B is not reloaded.
Is it possible to add a parameter in the configuration of Get() so that only the last page is reloaded if the user presses the back button?

**Comment by jonataslaw** [comment]
Hi, this is not a side effect. In Flutter, returning from a route does not call initState again, because the previous route is not a new route, it is just a route that is below the current one. This behavior is expected, not only for Get but also for Flutter.
However, there is a lot you can do with Get to work around this.
If you want to give a setState when you return to route B, just put in Get.to(C()) on your page B an await and then give a setState:
```dart
onPressed:() async { // you need add async to your method
await Get.to(C()); 
setState ((){});
}
```
If you intend to call methods that are in initState, coming back from a route, this is impossible with default Flutter. The Flutter team has already manifested itself by the impossibility of the resource, and in the stackoverflow you will not find an answer to that.
Fortunately with Get's advanced API it makes this possible by using a MiddleWare to perform an action whenever a specific route is in the foreground, you can see an example of this in

https://github.com/jonataslaw/get/issues/31

Closing this because it is standard behavior, but if you have any questions, you can comment here.
If you find a bug, do not hesitate to open another issue.

**Comment by suleymanbilgin** [comment]
@jonataslaw you said use setState and refresh that page but it is not working on classes that extends from GetView screens. I found Get.appForceUpdate() but it is refreshing all screens from starting of app.

**Comment by jonataslaw** [comment]
> @jonataslaw you said use setState and refresh that page but it is not working on classes that extends from GetView screens. I found Get.appForceUpdate() but it is refreshing all screens from starting of app.

This issue is from the time of Get 1.0 that had no state management.
Currently you should use an update() if you are using GetBuilder on your screen, or an Obx if the data is observable, and insert this into your controller, instead of your view.

**Comment by Suhailakl** [comment]
Same issue here. When I go back to the previous page the widgets in that screen won't reload. Because of that If a widget i changed on the 2nd screen won't change when I go back to the previous screen

**Comment by SimplicitySpace** [comment]
Hello 
Is there a version of onPressed:() async { // you need add async to your method
await Get.to(C()); 
setState ((){});
} incase im routing within business logic
