### ISSUE TITLE
How do we add another observer?

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/get#65]
In previous versions of get, you were still using MaterialApp and adding a Middleware to the navigationObservers.

But on your latest builds, you now have a GetMaterialApp with a routingCallback. But that doesn't seem to take an array. So how can we add another observer than our regular one? Specifically, I'm trying to add Firebase Analytics which they tell you to add a navigationObserver.

```
MaterialApp(
  home: MyAppHome(),
  navigatorObservers: [
    FirebaseAnalyticsObserver(analytics: analytics),
  ],
);
```

How would we use Analytics with this library while also keeping the Middleware?

Thanks!

**Comment by jonataslaw** [comment]
```dart
GetMaterialApp(
  home: MyAppHome(),
  routingCallback: Middleware.routing,
  navigatorObservers: [
    FirebaseAnalyticsObserver(analytics: analytics), // GetObserver left here, you don't need it anymore, use routingCallback when you need a MiddleWare and use navigatorObserver normally.
  ],
);
```
RountingCallback is only for Get middleware. You can use navigatorObserver as usual

**Comment by jlubeck** [comment]
Oh, pfff. Stupid me.

Out of curiosity, may I ask why you create a different callback if you were using the navigatorObservers before? I'm still closing this one. Thanks!

**Comment by jonataslaw** [comment]
> Oh, pfff. Stupid me.
> 
> Out of curiosity, may I ask why you create a different callback if you were using the navigatorObservers before? I'm still closing this one. Thanks!

The GetObserver API became mandatory due to the advanced features of 2.0, so I built it internally, and exposed it in the GetMaterialApp as a callback, since normal Observers are not middlware, and I think it was a little out of place and meaningless. This also allowed the logs to be turned on and off directly from GetMaterialApp, and dozens more new functions, related to the state manager and instance manager (when you navigate a route that does not use the controller, Get removes the controller from memory to you, GetObserver is used in everything, including state and route managers now)
