### ISSUE TITLE
NamedRoutes are not resolving correctly

### ISSUE THREAD

**Issue by ozasadnyy** [jonataslaw/get#67]
**Describe the bug**
`namedRoutes` are not resolving correctly. In this example if you go to any of these routes, you will be redirected to the last defined path (here `FavoriteCocktailsView()`);
```dart
namedRoutes: {
	'/cocktails': GetRoute(page: CocktailsView()),
	'/cocktails/:id': GetRoute(page: CocktailDetailsView()),
	'/favorite/cocktails': GetRoute(page: FavoriteCocktailsView()),
}

```

**To Reproduce**
1. Set `namedRoutes` as follow:
```dart
namedRoutes: {
	'/cocktails': GetRoute(page: CocktailsView()),
	'/cocktails/:id': GetRoute(page: CocktailDetailsView()),
	'/favorite/cocktails': GetRoute(page: FavoriteCocktailsView()),
} 
```
1. `Get.toNamed('/cocktails/negroni')`
1. See error `FavoriteCocktailsView()` is opening;

**Expected behavior**
Open `CocktailDetailsView()`

**Flutter Version:**
Flutter (Channel beta, v1.17.0-3.4.pre, on Mac OS X 10.15.4 19E287, locale en-GB)

**Get Version:**
get: ^2.0.9-dev

**Describe on which device you found the bug:**
ex: Emulator iPhone 11 (13.4.1)

**Comment by jonataslaw** [comment]
Hi, thanks for opening this issue.
Initially, I need to clarify that you are not using the lib as I designed it to be used.
I really appreciate stability, and because of that, the library only has resources taken to branch stable that have been thoroughly tested in almost any situation.
I see that you are wanting to define two identical routes, one with parameters, and one without, and forward a different route when there is a parameter.
In theory, this can even be legal, because you delegate the responsibility to the route manager to check whether a route is null or not, or it can be legal for design reasons.
In practice, you would be creating a perfect route, and another ghost route, which would depend on a parameter sent by Get.toNamed to exist. In my view, this can have unwanted effects, simply because you have to ignore onUnknownRoute in some situations to have this functional API. Especially on the web, this could cause problems, and it simply cannot be tested.

```dart
namedRoutes: {
	'/cocktails': GetRoute(page: CocktailsView()),

         /// In this line you are basically creating two identical named routes, assigning one parameter 
         /// null, and the other creating an object id.
	'/cocktails/:id': GetRoute(page: CocktailDetailsView()),      
	'/favorite/cocktails': GetRoute(page: FavoriteCocktailsView()),
}
```

You can create other router:
`'/cocktails/id/:id': GetRoute(page: CocktailDetailsView()), `

out: url/cocktails/id/12345

or use web syntax

'/cocktails': GetRoute(page: CocktailsView()),
'/cocktails/id': GetRoute(page: CocktailDetailsView()),      
'/favorite/cocktails': GetRoute(page: FavoriteCocktailsView()),

Get.toNamed("/cocktails/id?1234");

Keep in mind that creating an Object as a parameter does not mean creating a new route, and if you need to hide part of the parameter, just like in the web language, you can use url rewrites, like htaccess in apache, or nginx rewrites (in web side, if you're programming mobile / desktop, I can't think of a good reason to use a new route without typing it).
Obviously, there is a way to make a workaround to work that way, which I would not recommend (giving an abstract name for the route and replacing between the pushing of the route, and the receipt of it by the MaterialApp), as this can have side effects on onUnknownRoute and the general security of the route code, since we would have no way of predicting which routes could be used (maybe dynamic routes are not that dynamic).
Well, I'm going to do an update right now, and I'm going to add an undocumented super, mega, blaster, hyper experimental API, which you can use if you are in the beta / dev / master branch. I am not going to document this, because I know the risk involved, and I would be ashamed of anyone looking at the related code, because it is in fact a gambiarra ("if" /: "is present in the routes, create a phantom route and name it as soon as you receive the parameter sent in Get.toNamed)
If I ever find a safe way to do this, I backport to stable, but honestly, that for me will never be safe enough, as we are creating ghost routes, and giving the user the power to define them through parameters.
