### ISSUE TITLE
Full featured Sample App

### ISSUE THREAD

**Issue by NiranjanShah** [jonataslaw/get#77]
"get" seems to be promising widget. Being very NEW to flutter and after going thru 2 State Management library, the syntax and fundamentals of "GET" seems to be promising (PS: I am very new to Flutter).

Providing a real life sample app, using the functionality of "GET" will be very helpful for all the freshers who need to move to Flutter. 

UI for a app being developed by me has been completed, however for State Management solution, I have put almost 2 weeks to finalise the approach.

Hence, providing various sample app using the "GET" functionality will be very very useful.

Also can you change the name of the widget, reason being when search on Google will be done , get will be very common word and right reference to this widget may be hard to find.

**Comment by NiranjanShah** [comment]
A sample Shopping Cart example with login and category / product listing must be quite useful for people moving to flutter.

**Comment by jonataslaw** [comment]
Hi. the example application (corona virus application) uses Get's route manager, state manager and dependency manager.
To implement something like a shopping cart, you can use the same logic as the example controller.
The corona virus information is available on all other screens, and if they were changed on another screen, it would update all widgets that use the variable that was changed (that are inside a GetBuilder).
Sorry, but I have concentrated my effort on ensuring the stability of the library, and adding new features, but you can copy any code you use with setState on a page and insert it into your controller, removing setState and adding the update below the variable changed to make it available on all pages that need it, and despite having absurdly superior performance (in the absence of changeNotifier) ​​and under the hood being totally different, the syntax is also similar to the Provider, Exchanging a Consumer for a GetBuilder , and ignoring things like multiproviders, providers, and the like.
I understand your positioning, but for me it would be a waste of human resources to create a new app with this functionality, since the sample application already shows how to use the necessary resources to do what you want. I am basically the only maintainer of this library that houses route, dependency and state manager, and in addition I have 2 jobs. Creating a sample app would be the same as sacrificing a new feature.
Furthermore, any sample app built with Provider, Mobx, or anything else, can be transferred to Get just by exchanging Observer / Consumer for GetBuilder, and removing all cliche code (in mobx annotations, in Provider, Provider, multiproviders, or anything like that).
Sorry, but I think it is necessary to make another sample application at the moment.

If you encounter any problem with Get, do not hesitate to open another issue.
If you have questions about my answer, you can comment here, which I will answer in the same way.
Closing this

**Comment by ChickenAhn** [comment]
@jonataslaw 
Is there any example with `auto_route` package?
I love these packages but how can I use both?

auto_route generate router for me and it use extended navigator itself.
[https://pub.dev/packages/auto_route]

Thanks

**Comment by jonataslaw** [comment]
> @jonataslaw
> Is there any example with `auto_route` package?
> I love these packages but how can I use both?
> 
> auto_route generate router for me and it use extended navigator itself.
> [auto_route](https://pub.dev/packages/auto_route)
> 
> Thanks

Well, if you want to use Get's instance manager and dependency manager. you can simply add the package and use it together with auto_route.
However, you would miss the very low level APIs that Get has (knowing which screen is open at that moment, triggering events when a route is in the foreground, calling snackbars from anywhere in the code without context, etc.).
I don't know what would be the advantage of using them together, since Get does everything that auto_route does, without a code generator, in an easier way (except the syntactic sugar of the "routeGuards" that I will probably implement in Get just to say : I created it just to have in the description, don't use it, guards rule should never be in the client!).
Get's focus is precisely to have everything to a minimum. Manage routes, states, and dependencies with a single ultra-light library and don't need to add other packages to your project. Obviously you can use auto_route for routes, Get for state management and get_it for dependency injection, if you prefer to work like this, but that would only make your project bloated, which is just the opposite of the premise of this library.

**Comment by nothinggift** [comment]
I really don’t consider flutter_web. I used auto_router before, but I don’t like code generators, named routes cannot provide effective code hints. In flutter, I didn’t find any advantages of named routes.
