### ISSUE TITLE
dialog error child == null

### ISSUE THREAD

**Issue by GUIKAR741** [jonataslaw/get#8]
Hi, i am Brazilian and first i want to thank you for this amazing library.

i found this error "'package:get/src/routes.dart': Failed assertion: line 112 pos 12: 'child == null': is not true." when call 
```dart 
Get.dialog()
```

I managed to fix it by changing the following line

https://github.com/jonataslaw/get/blob/f64d4a35d51fc7a21cd68f1283f52873f10cee21/lib/src/routes.dart#L112

to

```dart 
assert(child != null)

**Comment by jonataslaw** [comment]
> Hi, i am Brazilian and first i want to thank you for this amazing library.
> 
> i found this error "'package:get/src/routes.dart': Failed assertion: line 112 pos 12: 'child == null': is not true." when call
> 
> ```dart
> Get.dialog()
> ```
> 
> I managed to fix it by changing the following line
> 
> https://github.com/jonataslaw/get/blob/f64d4a35d51fc7a21cd68f1283f52873f10cee21/lib/src/routes.dart#L112
> 
> to
> 
> ```dart
> assert(child != null)
> ```

First, thanks for this issue, I made this update at 4:30 am, because I was busy and wanted to keep the library active, and the lack of coffee made me insert an "==" instead of "! =" In the assert.
Your solution also works, as there will be no nullity check on the child, however, if someone opens a dialog without a child, there will not be a warning saying that it is mandatory, so I changed the operators and am upgrading to version 1.7.4 now.
I am happy to see someone from the Brazilian community using this lib, and this great framework shows that we are gaining strength, which is incredible. If you face any problem, do not hesitate to inform.

**Comment by GUIKAR741** [comment]
Thanks for solving this problem.
