### ISSUE TITLE
Wrong information about provider + ChangeNotifier

### ISSUE THREAD

**Issue by rrousselGit** [jonataslaw/get#99]
The readme mentions that provider+ChangeNotifier is not scalable as ChangeNotifer is O(N^2)

But that is not true.

When using provider, there's only one listener on the ChangeNotifier.
Instead updates are done through InheritedWidgets, which is O(N) and therefore without the mentioned issue.

**Comment by jonataslaw** [comment]
> The readme mentions that provider+ChangeNotifier is not scalable as ChangeNotifer is O(N^2)
> 
> But that is not true.
> 
> When using provider, there's only one listener on the ChangeNotifier.
> Instead updates are done through InheritedWidgets, which is O(N) and therefore without the mentioned issue.

Hi, thanks for commenting. I just mentioned that most state managers use ChangeNotifier as well as the Provider (which is the best known case of changeNotifier), not that the provider uses 2 listeners, so there is no incorrect information at this point, but obviously, you may not like the reference to the Provider, or would like it to be presented in another way.

I can change the readme to not contain the reference to the provider, or mention that the provider uses inheritedWidget to have only one listener, whichever you prefer.

The readme's intention is to point out the differences between the state managers for people to decide whether to use the standard Get state manager, or to use Get in conjunction with another one (Get is not just a state manager, there are people who use provider together with Get to open snackbars or navigate between routes according to an event within the ChangeNotifier class, there are people who use Get with MobX, there are people who use Get with BLoC) and obviously, the goal is not to say that people should abandon their state managers, but in what situation should they use the Get state manager or another, because Get is NOT a state manager, but a microframework that can be used with anything, both in a 'vanilla' way as in together with other state managers, offering many APIs that are not present in pure Flutter (such as callbacks like Get.isSnackbar / dialogIsOpen, etc.).

**Comment by rrousselGit** [comment]
> or mention that the provider uses inheritedWidget to have only one
listener, whichever you prefer.

This would be preferable, thanks 😊

**Comment by jonataslaw** [comment]
Readme updated, thanks.
